# Generated by Django 4.2.3 on 2024-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('providerAccountId', models.CharField(max_length=255)),
                ('refresh_token', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('expires_at', models.BigIntegerField(null=True)),
                ('id_token', models.TextField(null=True)),
                ('scope', models.TextField(null=True)),
                ('session_state', models.TextField(null=True)),
                ('token_type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('expires', models.DateTimeField()),
                ('sessionToken', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emailVerified', models.DateTimeField()),
                ('image', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('expires', models.DateTimeField()),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'verification_tokens',
                'managed': True,
            },
        ),
    ]
