# Generated by Django 4.2.3 on 2024-09-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_user_email_alter_user_emailverified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('completed', 'Completed'), ('deferred', 'Deferred'), ('deleted', 'Deleted')], max_length=255)),
                ('dueDate', models.DateTimeField(null=True)),
                ('completedDate', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('task', 'Task'), ('note', 'Note'), ('grocery', 'Grocery')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.user')),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
            },
        ),
    ]
