# Generated by Django 5.1.1 on 2024-09-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_session_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'managed': True, 'ordering': ['expires']},
        ),
    ]
