# Generated by Django 5.1.1 on 2024-09-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_session_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
